sudo: required
services:
  - docker

before_install:
  - docker build -t dragosal72/docker-react -f Dockerfile.dev .

script:
  - docker run dragosal72/docker-react npm run test -- --coverage
 # - docker run -e CI=true dragosal72/docker-react npm run test